apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-es-pv
  labels:
    logging: logging-es 
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /ocp/logging
  persistentVolumeReclaimPolicy: Retain
