apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pv
  labels:
    metrics-infra: hawkular-cassandra
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /ocp/metrics
  persistentVolumeReclaimPolicy: Retain
