apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  generation: 22
  labels:
    name: gitlab-runner
  name: gitlab-runner
  namespace: devops
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  selector:
    matchLabels:
      name: gitlab-runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: gitlab-runner
    spec:
      containers:
        - args:
            - run
          image: 'gitlab/gitlab-runner:latest'
          imagePullPolicy: Always
          name: gitlab-runner
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /.gitlab-runner
              name: gitlab-runner
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: gitlab-runner
          name: gitlab-runner