apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Crunchy Metrics
    iconClass: icon-database
    tags: database,postgresql,replication,metrics
  creationTimestamp: null
  name: crunchy-metrics
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAMESPACE}-metrics-prometheusdata-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${METRICS_PROMETHEUS_STORAGE_SIZE}
    selector:
      matchLabels:
        postgres: ${NAMESPACE}-metrics-prometheusdata
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAMESPACE}-metrics-grafanadata-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${METRICS_GRAFANA_STORAGE_SIZE}
    selector:
      matchLabels:
        postgres: ${NAMESPACE}-metrics-grafanadata
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: ${CRUNCHY_METRICS_SERVICE_NAME}
    name: ${CRUNCHY_METRICS_SERVICE_NAME}
  spec:
    ports:
    - name: prometheus
      nodePort: 0
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: grafana
      nodePort: 0
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      name: ${CRUNCHY_METRICS_SERVICE_NAME}
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${CRUNCHY_METRICS_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${CRUNCHY_METRICS_SERVICE_NAME}
    strategy:
      activeDeadlineSeconds: 864001
      recreateParams:
        timeoutSeconds: 864000
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${CRUNCHY_METRICS_SERVICE_NAME}
          replicatype: trigger
      spec:
        serviceAccountName: prometheus-sa
        nodeSelector:
          kubernetes.io/hostname: ${PG_NODE}
        containers:
        - env: []
          image: ${CCP_IMAGE_PREFIX}/crunchy-prometheus:${CCP_IMAGE_TAG}
          name: crunchy-prometheus
          ports:
          - containerPort: 9090
            protocol: TCP
          volumeMounts:
          - mountPath: /data
            name: prometheusdata
            readOnly: false
        - env:
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: admin-username
                name: crunchy-metrics-secret
          - name: ADMIN_PASS
            valueFrom:
              secretKeyRef:
                key: admin-password
                name: crunchy-metrics-secret
          - name: PROM_HOST
            value: ${CRUNCHY_METRICS_SERVICE_NAME}
          - name: PROM_PORT
            value: '9090'
          image: ${CCP_IMAGE_PREFIX}/crunchy-grafana:${CCP_IMAGE_TAG}
          name: crunchy-grafana
          ports:
          - containerPort: 3000
            protocol: TCP
          volumeMounts:
          - mountPath: /data
            name: grafanadata
            readOnly: false
        volumes:
        - name: prometheusdata
          persistentVolumeClaim:
            claimName: ${NAMESPACE}-metrics-prometheusdata-pvc
        - name: grafanadata
          persistentVolumeClaim:
            claimName: ${NAMESPACE}-metrics-grafanadata-pvc
parameters:
- description: project namespace
  name: NAMESPACE
  value: changeit
- description: The image prefix to use
  name: CCP_IMAGE_PREFIX
  value: crunchydata
- description: The image tag to use
  name: CCP_IMAGE_TAG
  value: centos7-10.3-1.8.2
- description: The kubernetes node label where the primary database container should run.
  name: PG_NODE
  value: ocp-node-01.example.com
- description: crunchy metrics service
  name: CRUNCHY_METRICS_SERVICE_NAME
  value: crunchy-metrics
- description: Requested size of prometheus metrics data volume
  name: METRICS_PROMETHEUS_STORAGE_SIZE
  value: 2Gi
- description: Requested size of grafana metrics data volume
  name: METRICS_GRAFANA_STORAGE_SIZE
  value: 2Gi
