apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Persistent volumes needed for PostgreSQL defined as sandbox example.
    iconClass: icon-database
    tags: database,postgresql,crunchy,metrics
  creationTimestamp: null
  name: crunchy-metrics-vols
objects:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      postgres: ${NAMESPACE}-metrics-prometheusdata
    name: ${NAMESPACE}-metrics-prometheusdata-pv
  spec:
    claimRef:
      name: ${NAMESPACE}-metrics-prometheusdata-pvc
      namespace: ${NAMESPACE}
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: ${METRICS_PROMETHEUS_STORAGE_SIZE}
    hostPath:
      path: ${METRICS_PROMETHEUS_PV_PATH}
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      postgres: ${NAMESPACE}-metrics-grafanadata
    name: ${NAMESPACE}-metrics-grafanadata-pv
  spec:
    claimRef:
      name: ${NAMESPACE}-metrics-grafanadata-pvc
      namespace: ${NAMESPACE}
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: ${METRICS_GRAFANA_STORAGE_SIZE}
    hostPath:
      path: ${METRICS_GRAFANA_PV_PATH}
    persistentVolumeReclaimPolicy: Retain
parameters:
- name: NAMESPACE
  value: project
- description: Host path of prometheus repo.
  name: METRICS_PROMETHEUS_PV_PATH
  value: /var/appdata/namespace/metrics-prometheus
- description: Host path of grafana repo.
  name: METRICS_GRAFANA_PV_PATH
  value: /var/appdata/namespace/metrics-grafana
- description: Requested size of prometheus volume
  name: METRICS_PROMETHEUS_STORAGE_SIZE
  value: 2Gi
- description: Requested size of grafana volume
  name: METRICS_GRAFANA_STORAGE_SIZE
  value: 2Gi

