apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Crunchy Metrics
    iconClass: icon-database
    tags: database,postgresql,replication,metrics
  creationTimestamp: null
  name: crunchy-metrics
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAMESPACE}-crunchy-metrics-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${CRUNCHY_METRICS_STORAGE_SIZE}
    selector:
      matchLabels:
        postgres: ${NAMESPACE}-crunchy-metrics
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: ${CRUNCHY_METRICS_SERVICE_NAME}
    name: ${CRUNCHY_METRICS_SERVICE_NAME}
  spec:
    ports:
    - name: grafana
      nodePort: 0
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: prometheus
      nodePort: 0
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: promgateway
      nodePort: 0
      port: 9091
      protocol: TCP
      targetPort: 9091
    selector:
      name: ${CRUNCHY_METRICS_SERVICE_NAME}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${CRUNCHY_METRICS_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${CRUNCHY_METRICS_SERVICE_NAME}
    strategy:
      activeDeadlineSeconds: 864001
      recreateParams:
        timeoutSeconds: 864000
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${CRUNCHY_METRICS_SERVICE_NAME}
          replicatype: trigger
      spec:
        nodeSelector:
          kubernetes.io/hostname: ${PG_NODE}
        containers:
        - env: []
          image: ${CCP_IMAGE_PREFIX}/crunchy-prometheus:${CCP_IMAGE_TAG}
          name: crunchy-prometheus
          ports:
          - containerPort: 9090
            protocol: TCP
          volumeMounts:
          - mountPath: /data
            name: metrics
            readOnly: false
        - env: []
          image: ${CCP_IMAGE_PREFIX}/crunchy-promgateway:${CCP_IMAGE_TAG}
          name: crunchy-promgateway
          ports:
          - containerPort: 9091
            protocol: TCP
          volumeMounts: []
        - env: []
          image: ${CCP_IMAGE_PREFIX}/crunchy-grafana:${CCP_IMAGE_TAG}
          name: crunchy-grafana
          ports:
          - containerPort: 3000
            protocol: TCP
          securityContext:
            capabilities: {}
          volumeMounts:
          - mountPath: /data
            name: metrics
            readOnly: false
        volumes:
        - name: metrics
          persistentVolumeClaim:
            claimName: ${NAMESPACE}-crunchy-metrics-pvc
parameters:
- description: project namespace
  name: NAMESPACE
  value: changeit
- description: The image prefix to use
  name: CCP_IMAGE_PREFIX
  value: crunchydata
- description: The image tag to use
  name: CCP_IMAGE_TAG
  value: centos7-10.3-1.8.1
- description: The kubernetes node label where the primary database container should run.
  name: PG_NODE
  value: ocp-node-01.example.com
- description: crunchy metrics service
  name: CRUNCHY_METRICS_SERVICE_NAME
  value: crunchy-metrics
- description: Requested size of metrics data volume
  name: CRUNCHY_METRICS_STORAGE_SIZE
  value: 2Gi
