apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Crunchy Metrics
    iconClass: icon-database
    tags: database,postgresql,replication
  creationTimestamp: null
  name: crunchy-metrics-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: crunchy-metrics-secret
  stringData:
    admin-password: ${ADMIN_PASS}
    admin-username: ${ADMIN_USER}
  type: opaque
parameters:
- description: metrics admin user
  value: admin
  name: ADMIN_USER
- description: metrics admin password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: ADMIN_PASS
