apiVersion: v1
kind: Template
metadata:
  annotations:
    description: gitlab-runner
    iconClass: icon-database
    tags: devops, gitlab
  creationTimestamp: null
  name: gitlab-runner
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: gitlab-runner
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: gitlab-runner
    template:
      metadata:
        labels:
          name: gitlab-runner
      spec:
        containers:
        - args:
          - run
          image: ${IMAGE_REF}
          imagePullPolicy: Always
          name: gitlab-runner
          volumeMounts:
          - mountPath: /etc/gitlab-runner
            name: config
          - mountPath: /etc/ssl/certs
            name: cacerts
            readOnly: true
        restartPolicy: Always
        volumes:
        - configMap:
            name: ${GITLAB_CONFIG_NAME}
          name: config
        - hostPath:
            path: /usr/share/ca-certificates/mozilla
          name: cacerts
          securityContext:
            privileged: true
        serviceAccountName: gitlab
parameters:
- description: gitlab image
  name: IMAGE_REF
  value: gitlab/gitlab-runner:v10.7.2
- description: repository configmap
  name: GITLAB_CONFIG_NAME
  value: java-crypto

