apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pg-backrest-restore-interactive
  annotations:
    description: Crunchy BackRest - pod for interactive commanline restore.
    tags: database,postgresql,replication,backrest
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: pg-backrest-restore-interactive
  spec:
    nodeSelector:
      kubernetes.io/hostname: ${PG_NODE}
    containers:
    - name: pg-backrest-restore-interactive
      image: ${CCP_IMAGE_PREFIX}/crunchy-backrest-restore:${CCP_IMAGE_TAG}
      command: ["/bin/bash"]
      args: ["-c", "while true; do echo heartbeat; sleep 30;done"]
      volumeMounts:
      - mountPath: /pgdata
        name: pgdata
        readOnly: false
      - mountPath: /backrestrepo
        name: backrestrepo
        readOnly: false
      - mountPath: /pgconf
        name: pgconf
        readOnly: true
    restartPolicy: Never
    securityContext:
      supplementalGroups:
      - 65534
    volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: ${NAMESPACE}-${PG_MODE}-data-pvc
    - name: backrestrepo
      persistentVolumeClaim:
        claimName: ${NAMESPACE}-${PG_MODE}-backrestrepo-pvc
    - name: pgconf
      configMap:
        name: pgconf
        items:
        - key: pgbackrest
          path: pgbackrest.conf
parameters:
- description: project namespace
  name: NAMESPACE
  value: changeit
- description: The image prefix to use
  name: CCP_IMAGE_PREFIX
  value: crunchydata
- description: The image tag to use
  name: CCP_IMAGE_TAG
  value: centos7-10.2-1.8.0
- description: The kubernetes node label where the primary database container should run.
  name: PG_NODE
  value: ocp-node-01.example.com
- description: Mode of postgres (replica or primary)
  name: PG_MODE
  value: primary

