apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Crunchy PostgreSQL 
    iconClass: icon-database
    tags: database,postgresql,replication
  creationTimestamp: null
  name: pg-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: pg-secret
  stringData:
    pg-primary-password: ${PG_PRIMARY_PASSWORD}
    pg-primary-username: ${PG_PRIMARY_USER}
    pg-password: ${PG_PASSWORD}
    pg-root-password: ${PG_ROOT_PASSWORD}
    pg-username: ${PG_USER}
  type: opaque
parameters:
- description: PostgreSQL application username
  value: sandbox
  name: PG_USER
- description: PostgreSQL application password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: PG_PASSWORD
- description: PostgreSQL root password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: PG_ROOT_PASSWORD
- description: PostgreSQL master user (often master)
  value: master
  name: PG_PRIMARY_USER
- description: PostgreSQL master password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: PG_PRIMARY_PASSWORD
