apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Sonarqube secrets
    iconClass: fa-bug
    tags: devops, code
  creationTimestamp: null
  name: sonarqube-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: sonarqube-secret
  stringData:
    db-password: ${SONARQUBE_DB_PASSWORD}
    db-username: ${SONARQUBE_DB_USER}
  type: opaque
parameters:
- description: Sonarqube database username
  value: sonar
  name: SONARQUBE_DB_USER
- description: Sonarqube database password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: SONARQUBE_DB_PASSWORD
